import type { FlightResult, DatePriceOption } from '@/types/flightResult';

export const MOCK_DATE_PRICES: DatePriceOption[] = [
  { date: 'Aug 10', dayName: 'Mon', price: 135 },
  { date: 'Aug 11', dayName: 'Tue', price: 128 },
  { date: 'Aug 12', dayName: 'Wed', price: 120, isSelected: true },
  { date: 'Aug 13', dayName: 'Thu', price: 125 },
  { date: 'Aug 14', dayName: 'Fri', price: 142 },
  { date: 'Aug 15', dayName: 'Sat', price: 155 },
  { date: 'Aug 16', dayName: 'Sun', price: 148 },
];

export const MOCK_FLIGHT_RESULTS: FlightResult[] = [
  {
    id: 'vn-128',
    airline: 'Vietnam Airlines',
    airlineLogo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=120&q=80',
    flightNumber: 'VN 128',
    departureTime: '08:00',
    arrivalTime: '09:30',
    departureAirport: 'SGN',
    arrivalAirport: 'DAD',
    departureCity: 'Ho Chi Minh City',
    arrivalCity: 'Da Nang',
    duration: '1h 30m',
    stops: 'Nonstop',
    price: 120,
    currency: '$',
    cabinClass: 'Economy',
    baggageIncluded: true,
    refundable: true,
    ecoBadge: '15% lower CO₂',
  },
  {
    id: 'vj-624',
    airline: 'VietJet Air',
    airlineLogo: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=120&q=80',
    flightNumber: 'VJ 624',
    departureTime: '10:15',
    arrivalTime: '11:45',
    departureAirport: 'SGN',
    arrivalAirport: 'DAD',
    departureCity: 'Ho Chi Minh City',
    arrivalCity: 'Da Nang',
    duration: '1h 30m',
    stops: 'Nonstop',
    price: 98,
    currency: '$',
    cabinClass: 'Economy',
    baggageIncluded: false,
    refundable: false,
  },
  {
    id: 'qh-152',
    airline: 'Bamboo Airways',
    airlineLogo: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=120&q=80',
    flightNumber: 'QH 152',
    departureTime: '13:45',
    arrivalTime: '15:15',
    departureAirport: 'SGN',
    arrivalAirport: 'DAD',
    departureCity: 'Ho Chi Minh City',
    arrivalCity: 'Da Nang',
    duration: '1h 30m',
    stops: 'Nonstop',
    price: 115,
    currency: '$',
    cabinClass: 'Economy',
    baggageIncluded: true,
    refundable: true,
  },
  {
    id: 'sq-178',
    airline: 'Singapore Airlines',
    airlineLogo: 'https://images.unsplash.com/photo-1520437358207-323b43b5752b?auto=format&fit=crop&w=120&q=80',
    flightNumber: 'SQ 178',
    departureTime: '16:20',
    arrivalTime: '21:50',
    departureAirport: 'SGN',
    arrivalAirport: 'DAD',
    departureCity: 'Ho Chi Minh City',
    arrivalCity: 'Da Nang',
    duration: '5h 30m',
    stops: '1 stop (SIN)',
    price: 245,
    currency: '$',
    cabinClass: 'Economy',
    baggageIncluded: true,
    refundable: true,
    ecoBadge: 'Premium Inflight Service',
  },
];
